# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.messageBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messageBrowser.setGeometry(QtCore.QRect(35, 70, 371, 351))
        self.messageBrowser.setObjectName("messageBrowser")
        self.textinput = QtWidgets.QTextEdit(self.centralwidget)
        self.textinput.setGeometry(QtCore.QRect(40, 460, 311, 31))
        self.textinput.setObjectName("textinput")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(360, 460, 71, 23))
        self.sendButton.setObjectName("sendButton")
        self.nameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameinput.setGeometry(QtCore.QRect(290, 40, 113, 20))
        self.nameinput.setObjectName("nameinput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Messenger"))
        self.textinput.setPlaceholderText(_translate("MainWindow", "Введите сообщение..."))
        self.sendButton.setText(_translate("MainWindow", "отправить"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
